#!/bin/bash

set -euxo pipefail

sudo apt-get update -qq
sudo apt-get install -y acl attr libc6-dev fakeroot pandoc par2
sudo apt-get build-dep -y python-fuse python-pylibacl

sudo CFLAGS=-Wno-error=maybe-uninitialized pip install pyxattr
sudo pip install pylibacl

sudo apt-get install -y fuse pkg-config
sudo modprobe fuse
sudo chmod 666 /dev/fuse
sudo chown root:"$USER" /etc/fuse.conf
sudo pip install fuse-python
